Practical_10/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practical_10.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Practical_10/Controllers/ActionController.cs
using Practical_10.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practical_10.Controllers
{
    public class ActionController : Controller
    {
        // GET: Action
        public ActionResult Index()
        {
            return View();
        }

        public ContentResult ContentResult()
        {
            return Content("<h1>This is Content result returned");
        }
        public FileResult FileContentResult()
        {
            return File(Url.Content("~/Web.config"), "Text");
        }
        public EmptyResult EmptyResult()
        {
            return new EmptyResult();
        }
        public ActionResult JavaScriptResult()
        {
            return View();
        }
        public JavaScriptResult JavaScriptResultDemo()
        {
            var msg = "alert('You are rendering JavaScript Result from Action Method.');";
            return new JavaScriptResult() { Script = msg };
        }
        public JsonResult JsonResult()
        {
            var employee = new Employee() { Id = 1, Name = "Jay" };
            return Json(employee, JsonRequestBehavior.AllowGet);
        }
    }
}

Practical_10/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practical_10.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index(string id)
        {
            ViewBag.Name = id;
            return View();
        }
    }
}

Practical_10/Controllers/ExceptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practical_10.Controllers
{
    public class ExceptionController : Controller
    {
        // GET: Exception
        [HandleError(ExceptionType = typeof(DivideByZeroException), View = "~/Views/Error/DivideByZero.cshtml")]
        public ActionResult Index()
        {
            int num1 = 10, num2 = 0;
            var result = num1 / num2;
            ViewBag.Division = result;
            return View();
        }
    }
}

Practical_10/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practical_10.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Practical_10/Controllers/OutputCachedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practical_10.Controllers
{
    public class OutputCachedController : Controller
    {
        // GET: OutputCached

        [OutputCache(Duration = 300)]
        public ActionResult Index()
        {
            ViewBag.CurrentDate = DateTime.Now;
            return View();
        }
    }
}

Practical_10/Views/Action/ContentResult.cshtml
@{
    ViewBag.Title = "ContentResult";
}

<h2>ContentResult</h2>

Practical_10/Views/Action/EmptyResult.cshtml
@{
    ViewBag.Title = "EmptyResult";
}

<h2>This method is returning nothing so web page will be empty!</h2>

Practical_10/Views/Action/FileContentResult.cshtml
@{
    ViewBag.Title = "FileContentResult";
}

<h2>FileContentResult</h2>

Practical_10/Views/Action/Index.cshtml
@{
	ViewBag.Title = "Index";
}

<h2>Action Result</h2>
<hr />
<ul>
	<li><h5>Append <span class="text-primary">/ContentResult</span> in current URL to view output of ContentResult.</h5><hr /></li>
	<li><h5>Append <span class="text-primary">/FileContentResult</span> in current URL to view output of FileContentResult.</h5><hr /></li>
	<li><h5>Append <span class="text-primary">/EmptyResult</span> in current URL to view output of EmptyResult.</h5><hr /></li>
	<li><h5>Append <span class="text-primary">/JavaScriptResult</span> in current URL to view output of JavaScriptResult.</h5><hr /></li>
	<li><h5>Append <span class="text-primary">/JsonResult</span> in current URL to view output of JsonResult.</h5></li>
</ul>

Practical_10/Views/Action/JavaScriptResult.cshtml
@{
	ViewBag.Title = "JavaScriptResult";
}
<script src="~/Scripts/jquery-3.4.1.js"></script>

<h2>JavaScriptResult</h2>
<input type="button" id="btn" class="btn btn-danger" value="Get Alert" />

<script>
	$(document).ready(function () {
		$("#btn").click(function () {
			$.getScript("/Action/JavaScriptResultDemo");
		});
	});
</script>

Practical_10/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.Name</h2>

Practical_10/Views/Exception/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>>@ViewBag.Division</h2>

Practical_10/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Practical_10/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Practical_10/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Practical_10/Views/OutputCached/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.CurrentDate</h2>

Practical_10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Practical-10", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
				<ul class="navbar-nav flex-grow-1">
					<li>@Html.ActionLink("Test1", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
					<li>@Html.ActionLink("Test2", "Index", "Action", new { area = "" }, new { @class = "nav-link" })</li>
					<li>@Html.ActionLink("Test3", "Index", "OutputCached", new { area = "" }, new { @class = "nav-link" })</li>
					<li>@Html.ActionLink("Test4", "Index", "Exception", new { area = "" }, new { @class = "nav-link" })</li>
				</ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>